### ISSUE TITLE
add decimal separator preference in settings

### ISSUE THREAD

**Issue by idanyas** [Advaith3600/PowerToys-Run-Currency-Converter#20] opened 2024-10-30 09:27 UTC
add a setting to allow users to choose their preferred decimal separator format (dot or comma) for number inputs.

right now, the system automatically applies the separator based on the windows language, but it should be possible to override this in the settings. example options:
  - "Follow system language"
  - "Always use comma"
  - "Always use dot"

**Comment by idanyas** [comment] 2024-10-30 09:52
found a solution that doesn’t require changing the system language entirely. in windows, you can go to “Region settings” and adjust the decimal separator format there, but i still think it would be useful to have an option to switch it directly in the settings.
![regional format settings](https://github.com/user-attachments/assets/902c454a-1e4a-43a9-928d-0457a3f1939a)

you can open these settings by pressing Win + R, typing `intl.cpl`, and then selecting "Additional settings" where you'll find this option. but i still think it would be useful to have an option to switch it directly in the settings.

**Comment by Advaith3600** [comment] 2024-11-06 10:39
[CurrencyConverter-1.3.1-ARM64.zip](https://github.com/user-attachments/files/17645710/CurrencyConverter-1.3.1-ARM64.zip)
[CurrencyConverter-1.3.1-x64.zip](https://github.com/user-attachments/files/17645711/CurrencyConverter-1.3.1-x64.zip)

Can you try this and let me know?

**Comment by idanyas** [comment] 2024-11-06 11:34
thank you very much, the toggle in the settings works perfectly.

i might be nitpicking here, but could you also add an option to ignore spaces? as i understand it, the program follows regional formatting, so if numbers are formatted as '123 456 789', the converter follows this. when copying and pasting back or just using spaces in general, this can be a little inconvenient. if it's not too difficult, i’d appreciate it if you could implement this as well.
example 1:
![image](https://github.com/user-attachments/assets/b256652f-8473-49aa-8752-3e32cfdce0ad)
example 2:
![image](https://github.com/user-attachments/assets/8bb65b46-3fc4-4b82-af25-fcb92b702ef5)

![image](https://github.com/user-attachments/assets/a118334b-79e8-4516-a980-1d95d8344afb)

**Comment by Advaith3600** [comment] 2024-11-06 11:45
I didn't test it for all the edge cases, please let me know if this breaks at any point. Or you would like any other issue resolved. Always happy to help. 

[CurrencyConverter-1.3.1-x64.zip](https://github.com/user-attachments/files/17646539/CurrencyConverter-1.3.1-x64.zip)
[CurrencyConverter-1.3.1-ARM64.zip](https://github.com/user-attachments/files/17646540/CurrencyConverter-1.3.1-ARM64.zip)

**Comment by idanyas** [comment] 2024-11-09 14:41
If you just type with spaces - it works, but if you copy by clicking or pressing enter and then paste - it doesn't work:
![showcase GIF](https://github.com/user-attachments/assets/06f00a31-fcb5-4340-bce1-48c051ef73a0)

**Comment by Advaith3600** [comment] 2024-11-11 05:43
That is a really strange issue. I changed my formats to this and tried the steps you showed in the gif and it works fine for me.

![image](https://github.com/user-attachments/assets/52c46bc1-dac4-4d50-9bd6-125c74a141d7)


Can you try again to double-check that it happens every time and is not just a random network issue?

**Comment by Advaith3600** [comment] 2024-11-11 05:50
The query should have been resolved immediately as the currencies are cached, can you try the following if the issue is still there? Hopefully it fixes the issue.

[CurrencyConverter-1.3.1-x64.zip](https://github.com/user-attachments/files/17695880/CurrencyConverter-1.3.1-x64.zip)
[CurrencyConverter-1.3.1-ARM64.zip](https://github.com/user-attachments/files/17695881/CurrencyConverter-1.3.1-ARM64.zip)

**Comment by idanyas** [comment] 2024-11-11 12:58
doesn't seem to work. my regional formats:
![изображение](https://github.com/user-attachments/assets/c4ba941f-169e-4905-ae73-f306e876463e)

same behavior. if you remove the spaces, it seems to work.
![demonstration](https://github.com/user-attachments/assets/e9ea53d9-b2db-4674-95e5-915837fa9319)

**Comment by Advaith3600** [comment] 2024-11-20 07:18
I can't seem to reproduce the same issue, I have added some logging here, can you try this version and send me the logs once the issue starts occuring? You can find the logs at `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Logs`

[CurrencyConverter-1.3.1-ARM64.zip](https://github.com/user-attachments/files/17826602/CurrencyConverter-1.3.1-ARM64.zip)
[CurrencyConverter-1.3.1-x64.zip](https://github.com/user-attachments/files/17826603/CurrencyConverter-1.3.1-x64.zip)

**Comment by idanyas** [comment] 2024-11-25 04:25
Here's the logs and what I entered during that time. if it's useful, I have “Immediate plugins” set to 40 ms and “Background execution plugins” set to 120 ms in the Powertoys Run settings

[2024-11-25.txt](https://github.com/user-attachments/files/17897056/2024-11-25.txt)

![animation.gif](https://github.com/user-attachments/assets/e9b331a8-2980-485f-b12d-100118dae2f5)

**Comment by Advaith3600** [comment] 2024-11-28 09:32
The issue was with a different type of space, the plugin only checked for char code 32 and ignored other types of spaces like the non breaking (char code 160) used by your system. Now it should be handling all spaces correctly. Please try this and let me know, I will release the version once I cleanup the logs and after adding some other improvements. 

[CurrencyConverter-1.3.1-ARM64.zip](https://github.com/user-attachments/files/17945937/CurrencyConverter-1.3.1-ARM64.zip)
[CurrencyConverter-1.3.1-x64.zip](https://github.com/user-attachments/files/17945938/CurrencyConverter-1.3.1-x64.zip)

**Comment by Advaith3600** [comment] 2024-11-29 06:57
https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/releases/tag/v1.4.0

I am closing this issue right now, feel free to open it if the problem is not resolved or create a new one if there are any new issues. Thank you for your feedback and support.

**Closed by Advaith3600** 2024-11-29 06:57 UTC
